import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FC, ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Catalogar",
  // description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: ReactNode
}>

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <html lang="pt-br">
    <body className={inter.className}>
      {children}
    </body>
  </html>
)

export default RootLayout;
