name: CI

on:
  push:
    branches:
      - main
    paths:
      - apps/catalogar/**
      - packages/**
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-test:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # check out full history
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      # - name: Test
      #   run: pnpm test

      - name: Check Changeset
        run: pnpm changeset status --since=origin/main
